### PR TITLE
Discover test files from *_test packages

### PR DESCRIPTION
**Pull request by mattrx**

### CODE REVIEW

**Review by rpeshkov — CHANGES_REQUESTED** [review]
Thanks for your contribution!

There is 1 change need to be done:
Remove if statement on line 92 and add checks for length in if statements you introduced.

You need to remove if statement on line 92 because in the situation when you have only external tests, nothing will be displayed.

**Comment by mattrx** [comment]
Thank you, I missed the upper if statement. I changed the code.

**Comment by rpeshkov** [comment]
@mattrx Thank you once more for contribution! Extension update pushed to marketplace. Soon you'll receive update.

**Comment by mattrx** [comment]
I'm looking forward to it.

**Pull request merged**
